spring:
  mail:
    host: smtp.gmail.com # 서버 호스트
    port: 587 # 서버 포트
    username: ${mail.username} # 서버 로그인 아이디
    password: ${mail.password} # 서버 로그인 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)