spring:
  profiles:
    active: dev
  messages:
    basename: errors
  datasource:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      #개인적을 h2-console을 사용하기 위한 설정입니다. 이는 지우거나 무시해주세요.
      #spring.datasource.url= jdbc:h2:tcp://localhost/~/testgg
      #spring.datasource.username= sa
      #spring.datasource.password=
      #spring.datasource.driver-class-name= org.h2.Driver
      #
      #
      #spring.jpa.hibernate.ddl-auto= create-drop

  mail:
    host: smtp.gmail.com # 서버 호스트
    port: 587 # 서버 포트
    username: ${mail.username} # 서버 로그인용 이메일 (보안 문제로 환경설정에 설정)
    password: ${mail.password} # 서버 로그인용 비밀번호 (보안 문제로 환경설정에 설정)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  error:
    whitelabel:
      enabled: false
    path: /error
    include-exception: false
    include-message: never
